name 'build-cookbook'
maintainer 'Chef Supermarket Team'
maintainer_email 'supermarket@chef.io'
license 'Apache 2.0'
version '0.1.0'

depends 'fancy_execute'
depends 'languages'
depends 'chef-sugar'
depends 'docker', '~> 1.0'
